export const ADD_TO_COLLECTION = 'ADD_TO_COLLECTION'
export const REMOVE_FROM_COLLECTION = 'REMOVE_FROM_COLLECTION'
export const CLEAR_COLLECTION = 'CLEAR_COLLECTION'
export const RECEIVE_COLLECTION = 'RECEIVE_COLLECTION'
