export const DECREMENT_GLOBAL_LOADING_QUEUE = "DECREMENT_GLOBAL_LOADING_QUEUE";
export const INCREMENT_GLOBAL_LOADING_QUEUE = "INCREMENT_GLOBAL_LOADING_QUEUE";
export const TOGGLE_CATEGORY = "TOGGLE_CATEGORY";
export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE";
export const TOGGLE_NAME_SHOWS = "TOGGLE_NAME_SHOWS";
export const TOGGLE_REACTED = "TOGGLE_REACTED";
export const UPDATE_SEARCH = "UPDATE_SEARCH";
export const UPDATE_SIZE = "UPDATE_ICON_SIZE";
